--------------------------------------------------------
--  File created - Thursday-September-15-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADVERTISER_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADVERTISER_TABLE" 
   (	"ADVERTISERUSER" VARCHAR2(200 BYTE), 
	"ADID" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"THEMEIMAGE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(400 BYTE), 
	"IMAGE1" VARCHAR2(200 BYTE), 
	"IMAGE2" VARCHAR2(200 BYTE), 
	"IMAGE3" VARCHAR2(200 BYTE), 
	"VIDEO" VARCHAR2(200 BYTE), 
	"CATEGORY" VARCHAR2(200 BYTE), 
	"SUBCATEGORY" VARCHAR2(200 BYTE), 
	"PRIORTY" NUMBER, 
	"APPROVE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADVERTISER_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADVERTISER_TABLE_PK" ON "SYSTEM"."ADVERTISER_TABLE" ("ADVERTISERUSER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADVERTISER_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADVERTISER_TABLE" ADD CONSTRAINT "ADVERTISER_TABLE_PK" PRIMARY KEY ("ADVERTISERUSER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."ADVERTISER_TABLE" MODIFY ("ADVERTISERUSER" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ADVERTISER_TABLE" MODIFY ("ADID" NOT NULL ENABLE);
